# fly.toml app configuration file generated for livekit-server-lively-moon-9428 on 2025-10-15T22:37:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'livekit-server-lively-moon-9428'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'livekit_data'
  destination = '/data'

[http_service]
  internal_port = 7880
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/'

[[services]]
  protocol = 'tcp'
  internal_port = 7882

  [[services.ports]]
    port = 7882

[[services]]
  protocol = 'udp'
  internal_port = 7881

  [[services.ports]]
    port = 7881

[[services]]
  protocol = 'tcp'
  internal_port = 7881

  [[services.ports]]
    port = 7881

[[services]]
  protocol = 'udp'
  internal_port = 3478

  [[services.ports]]
    port = 3478

[[services]]
  protocol = 'tcp'
  internal_port = 5349

  [[services.ports]]
    port = 5349

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
